---
- name: install homebrew
  shell: /bin/bash -c "$(sudo curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  tags:
    - initialize

- name: install homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - "homebrew/services"
    - "heroku/brew"
  tags:
    - initialize

- name: install core packages
  homebrew:
    name: [
      "wget",
      "gcc",
      "openssl@3",
      "cmake",
      "git",
      "git-lfs",
      "moreutils",
      "findutils",
      "gnupg",
      "grep",
      "screen",
      "pigz",
      "tree",
      "heroku",
      "azure-cli",
      "bash",
      "circleci",
      "coreutils",
      "exiftool",
      "ffmpeg",
      "flyscrape",
      "gnutls",
      "helm",
      "k3d",
      "kind",
      "kubernetes-cli",
      "minikube",
      "ripgrep",
    ]
    state: present
  tags:
    - initialize

- name: Generate SSH Key
  shell: "yes y | ssh-keygen -t rsa -b 4096 -C '{{inventory_hostname}}' -N '' -f $HOME/.ssh/id_rsa"
  tags:
    - initialize

- name: Pull down dotfiles
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/genomics-geek/dotfiles.git"
    dest: "{{ lookup('env','HOME') }}/.dotfiles"
    version: "master"
  tags:
    - initialize

- name: initialize dot files
  shell: "$HOME/.dotfiles/setup.sh"
  args:
    chdir: "{{ lookup('env','HOME') }}/.dotfiles"
  tags:
    - initialize
