---
- name: install cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=$HOME/Applications/"
  with_items:
    - "slack"
    - "skype"
    - "atom"
    - "vscodium"
    - "postman"
    - "github-desktop"
    - "google-drive"
    - "google-chrome"
    - "spotify"
    - "spotify-notifications"
    - "dbvisualizer"
  tags:
    - caskapps
