---
- name: install cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=$HOME/Applications/"
  with_items:
    - "slack"
    - "skype"
    - "atom"
    - "vscodium"
    - "postman"
    - "github"
    - "brave-browser"
    - "google-drive-file-stream"
    - "google-chrome"
    - "google-chrome-canary"
    - "spotify"
    - "spotify-notifications"
    - "dbvisualizer"
    - "lastpass"
  tags:
    - caskapps
