---
- name: install cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=$HOME/Applications/"
  with_items:
    - "slack"
    - "skype"
    - "atom"
    - "vscodium"
    - "postman"
    - "github"
    - "brave-browser"
    - "google-drive-file-stream"
    - "google-chrome"
    - "spotify"
    - "spotify-notifications"
    - "dbvisualizer"
    - "lastpass"
  tags:
    - caskapps

- name: install Atom packaages
  shell: "apm install {{ item }}"
  with_items:
    - "language-babel"
    - "editorconfig"
    - "linter-ui-default"
    - "linter"
    - "linter-eslint"
    - "linter-flake8"
    - "teletype"
    - "git-plus"
    - "highlight-selected"
    - "file-icons"
    - "ask-stack"
    - "autocomplete-python"
    - "script"
    - "prettier-atom"
    - "python-autopep8"
    - "atom-beautify"
    - "atom-ternjs"
    - "language-wdl"
  tags:
    - caskapps
