---
- name: install cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=$HOME/Applications/"
  with_items:
    - "slack"
    - "skype"
    - "atom"
    - "vscodium"
    - "postman"
    - "github"
    - "brave-browser"
    - "google-drive-file-stream"
    - "google-chrome"
    - "spotify"
    - "spotify-notifications"
    - "dbvisualizer"
    - "lastpass"
  tags:
    - caskapps

- name: install Atom packages
  shell: "apm install {{ item }}"
  with_items:
    - "language-babel"
    - "language-wdl"
    - "atom-jinja2"
    - "editorconfig"
    - "linter"
    - "linter-ui-default"
    - "linter-eslint"
    - "linter-flake8"
    - "teletype"
    - "git-plus"
    - "highlight-selected"
    - "file-icons"
    - "ask-stack"
    - "script"
    - "autocomplete-python"
    - "autocomplete-modules"
    - "prettier-atom"
    - "python-autopep8"
    - "markdown-preview-plus"
  tags:
    - caskapps

- name: Copy Atom configuration file
  copy:
    src: "{{ role_path }}/files/config.cson"
    dest: "{{ lookup('env','HOME') }}/.atom/config.cson"
  tags:
    - caskapps

- name: install VSCode packages
  shell: "code --install-extension {{ item }}"
  with_items:
    - "ms-python.python"
    - "ms-vscode.go"
    - "broadinstitute.wdl"
    - "broadinstitute.wdl-devtools"
    - "msjsdiag.debugger-for-chrome"
    - "formulahendry.code-runner"
    - "vscode-icons-team.vscode-icons"
    - "eamodio.gitlens"
    - "dbaeumer.vscode-eslint"
    - "esbenp.prettier-vscode"
    - "editorconfig.editorconfig"
    - "formulahendry.auto-close-tag"
    - "formulahendry.auto-rename-tag"
    - "coenraads.bracket-pair-colorizer"
    - "christian-kohler.npm-intellisense"
    - "christian-kohler.path-intellisense"
    - "eg2.vscode-npm-script"
    - "pflannery.vscode-versionlens"
    - "streetsidesoftware.code-spell-checker"
    - "apollographql.vscode-apollo"
  tags:
    - caskapps
