---
#- name: install openjdk
#  homebrew_cask:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - "temurin"
#  tags:
#    - languages


- name: install erlang, scala, go, nim, and python3
  homebrew:
    name: [
      "golang",
      "scala",
      "sbt",
    ]
    state: present
  tags:
    - languages


- name: install Java packages
  homebrew:
    name: [
      "maven",
      "jenv",
    ]
    state: present
  tags:
    - languages
