---
- name: install openjdk
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - "adoptopenjdk/openjdk"
  tags:
    - languages
    
- name: install erlang, scala, go, nim, and python3
  homebrew:
    name: [
      "erlang",
      "golang",
      "scala",
      "sbt",
      "nim",
      "python3",
    ]
    state: present
  tags:
    - languages

- name: install perl packages
  homebrew:
    name: [
      "perl-build",
      "plenv",
    ]
    state: present
  tags:
    - languages

- name: install Java packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "maven"
    - "jenv"
  tags:
    - languages
