---
- name: install erlang, scala, go, nim, and python3
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "erlang"
    - "golang"
    - "scala"
    - "sbt"
    - "nim"
    - "python3"
  tags:
    - languages

- name: install perl packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "perl-build"
    - "plenv"
  tags:
    - languages

- name: install openjdk
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - "adoptopenjdk/openjdk"
  tags:
    - languages

- name: install Java packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "maven"
    - "jenv"
  tags:
    - languages
